local wezKeyBinding = require("wezKeyBind")
local wezFont = require("wezFont")
local wezFontSize = require("wezFontSize")
local wezColorScheme = require("wezColorScheme")
local wezOpacity = require("wezOpacity")
local wezGradient = require("wezGradient")
-- local wezQuieckSelectPatterns = require("wezQuickSelectPatterns")
-- local wezImage = require("wezImage")

local config = {}
wezKeyBinding.apply_to_config(config)
wezFont.apply_to_config(config)
wezColorScheme.apply_to_config(config)
wezOpacity.apply_to_config(config)
-- wezImage.apply_to_config(config)
wezFontSize.apply_to_config(config)
require("wezFullScreen")
wezGradient.apply_to_config(config)
-- wezQuieckSelectPatterns.apply_to_config(config)
return config
